### ISSUE TITLE
the experimental results are not as good as the results presented in your paper?

### ISSUE THREAD

**Issue by ZHUXUHAN** [aa200647963/SGG-DHL#3]
Dear sir:
I repeated your open source transformer experiment, but found that the experimental results are not as good as the results presented in your paper and log files, its mr performance is excellent, but r performance is not good. Is there a problem of large fluctuations in this training process, because I see that your loss has been dynamically adjusted. Do you have any adjustment suggestions?

[log.txt](https://github.com/aa200647963/SGG-DHL/files/9286315/log.txt)

**Comment by aa200647963** [comment]
I carefully checked the uploaded code and re-ensured its correctness.
I read your log file and found that the recall dropped by about 1 point, possibly due to the device or random seed. Generally speaking, the results of my experiment on 3090 are the best. I suggest running more times.  The attached log file results are shown in the paper
[log.txt](https://github.com/aa200647963/SGG-DHL/files/9286575/log.txt)

**Comment by ZHUXUHAN** [comment]
> 

as you say, i run the code in v100, haha, if that's the case, it would be very interesting. The random seed problem is also a baffling one. I will try it again. By the way, could you please help me to check my log file to see if there are any additional operating errors?

**Comment by aa200647963** [comment]
If you use the code and script that I uploaded, there should be no error. The model and log file I shared in README.md are completely executed by the uploaded code and script. And I didn't find any wrong operation in your log file

**Comment by ZHUXUHAN** [comment]
> If you use the code and script that I uploaded, there should be no error. The model and log file I shared in README.md are completely executed by the uploaded code and script. And I didn't find any wrong operation in your log file

ok thank you very much, i will try.
